spring:
  application:
    name: imall-admin
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-bean-definition-overriding: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

server:
  servlet:
    context-path: /admin
    encoding:
      charset: utf-8

# Mybatis配置
mybatis-plus:
  #实体扫描，多个package用逗号或者分号分隔
  mapper-locations:
    - classpath*:/mapper/**/*.xml
    - classpath:/dao/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.imall.mbg.domain
  global-config:
    db-config:
      id-type: auto
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

jwt:
  tokenHeader: Authorization #JWT存储的请求头
  tokenHead: 'Bearer '  #JWT负载中拿到开头
  secret: imall-admin-secret #JWT加解密使用的密钥
  expiration: 86400 #JWT的超期限时间(60*60*24*1)

security:
  ignored:
    urls: #安全路径白名单
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /actuator/**
      - /druid/**
      - /user/login
      - /user/register
