server:
  port: 9000

spring:
  datasource:
    dynamic:
      datasource:
        asteriskcdrdb:
          url: jdbc:mysql://localhost:3306/asteriskcdrdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
          username: root
          password: root
  redis:
    host: localhost
    port: 6379
    # password:
    database: 1
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

third-party:
  checkToken: false
  checkTimestamp: false
  timestampLimit: 300
  # 明文请求
  plaintextRequest: true
  checkSign: false

# 启用Swagger
swagger:
  show: true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
#  file:
#    path: logs/
