server:
  port: 8100

spring:
  datasource:
    dynamic:
      datasource:
        asteriskcdrdb:
          url: jdbc:mysql://localhost:3306/asteriskcdrdb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&allowMultiQueries=true&useSSL=false
          username: root
          password: root
  redis:
    host: localhost
    port: 6379
    # password:
    database: 1
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

third-party:
  public-param:
    check-token: false # 是否校验token
    check-timestamp: false # 是否校验时间戳
    timestamp-limit: 300 # 校验的时间戳时长，单位：秒
    plaintext-request: true # 是否开启明文请求
    check-sign: false # 是否校验sign
    ip-whilte: 127.0.0.1;192.168.*
  secrets:
    alibaba: K81qX8vGOhuUMJOjmYOB9Q==
    tencent: K81qX8vGOhuUMJOjmYOB9Q==
  fegin:
    admin: http://localhost:8080/admin

swagger:
  show: true

logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss.SSS
  level:
    com.imall.thirdparty: debug
#  file:
#    path: logs/
