spring:
  application:
    name: imall-mbg
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  profiles:
    active: dev

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置@TableLogic注解)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl # 开启 mybatis-plus 日志打印

logging:
  level:
    com.imall: debug
